branches:
  - 'release-drafter'

categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'fix'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
